%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo({
  "fromAddress": "ESB-nonprod <enterpriseintegration-sbsesbnonprod-donotreply@sbs.com.au>",
  "toAddress": "EISupport@sbs.com.au",
  "subject": "Concur Employee Profile Creation - Provisioning Request Status",
  "content": "<?xml version='1.0' encoding='UTF-8'?>\n<html>\n  <body>\n    <h2>Concur Employee Profile Creation - Status</h2>\n    <h3>Summary</h3>\n    <table border=\"1\">\n      <tr>\n        <th>Response Status</th>\n        <td>Processed Provisioning Request Status</td>\n      </tr>\n      <tr>\n        <th>Processed Employee Ids</th>\n        <td>testuser23</td>\n      </tr>\n      <tr>\n        <th>Failed Employee Ids</th>\n        <td>testuser24 , testuser22 , testuser21</td>\n      </tr>\n    </table>\n    <h3>Error Record Details</h3>\n    <table border=\"1\">\n      <tr>\n        <th>EMP ID</th>\n        <th>Feed Record Number</th>\n        <th> Error Message</th>\n        <th>Field</th>\n        <th>Value</th>\n      </tr>\n      <tr>\n        <td rowspan=\"1\">testuser24</td>\n        <td rowspan=\"1\">41624</td>\n        <td>Request is unparsable, syntactically incorrect, or violates schema.</td>\n        <td></td>\n        <td>Required fields missing</td>\n      </tr>\n      <tr>\n        <td rowspan=\"1\">testuser22</td>\n        <td rowspan=\"1\">41625</td>\n        <td>Invalid User ID</td>\n        <td>Approver</td>\n        <td>testuser42</td>\n      </tr>\n      <tr>\n        <td rowspan=\"1\">testuser21</td>\n        <td rowspan=\"1\">41626</td>\n        <td>Invalid Permissions for 'urn:ietf:params:scim:schemas:extension:spend:2.0:Approver:report[0].approver'</td>\n        <td>Approver</td>\n        <td>testuser14</td>\n      </tr>\n    </table>\n  </body>\n</html>",
  "contentType": "text/html"
})