[
  {
    "FIRSTNAME": "test",
    "EXPENSEAPPROVER": null,
    "RECORD_STATUS": "CREATE",
    "CRNKEY": "AUD",
    "CUSTOM21": "SBS AU",
    "PASSWORD": null,
    "CUSTOM9": "000000",
    "LEDGERNAME": "Oracle",
    "CUSTOM3": "Technology Ops & Services",
    "CUSTOM1": "SBS Technology",
    "CUSTOM7": "21010",
    "CUSTOM8": "000000",
    "CUSTOM5": "N",
    "CUSTOM6": "10",
    "EMPID": "testuser23",
    "CTRYCODE": "AU",
    "LOGINID": "test.user23@sbs.com.au",
    "LOCALENAME": "en_US",
    "ISTESTEMP": "Y",
    "EXPENSEAPPROVEREMPLOYEEID": "testuser10",
    "ACTIVE": "Y",
    "EMAILADDRESS": "test.user23@sbs.com.au",
    "FEEDRECORDNUMBER": "41623",
    "LASTNAME": "user23",
    "CUSTOM10": "0000",
    "PROCESS_STATUS": null,
    "LEDGERKEY": "Oracle",
    "EXPENSEUSER": "Y"
  }
]